# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MonkeyKingDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MonkeyKingDemo

  target 'MonkeyKingDemoTests' do
    inherit! :search_paths
    # Pods for testing

pod 'WechatOpenSDK'
pod ‘TencentOpenApiSDK’ 
pod "Weibo_SDK", :git => "https://github.com/sinaweibosdk/weibo_ios_sdk.git" 
pod 'AlipaySDK-iOS'

  end

  target 'MonkeyKingDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
