
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '电力小助手' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 电力小助手

    pod 'Masonry'
  target '电力小助手Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '电力小助手UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
